---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
```

```{r}
evalFirstSystem <- function(m.g, 
                            m.icu, 
                            h.g_m, 
                            h.g_icu, 
                            h.icu_m){
  
  vec1 <- c(m.g, m.icu, 0, 0)
  vec2 <- c(h.g_icu, 1, 0, 0)
  vec3 <- c(h.g_m, h.icu_m, 1, 0)
  vec4 <- c(1, 1, 1, 1)
  
  ls <- rbind(vec1, vec2, vec3, vec4)
  
  rs <- rbind(m.g - 1, h.g_icu, h.g_m, 1)
  
  sol <- t(solve(ls, rs))
  colnames(sol) <- c('p.g_g', 'p.g_icu', 'p.g_m', 'p.g_d')
  return(sol[1,])
}
```



```{r}
evalSecondSystem <- function(m.icu, 
                             m.v, 
                             h.icu_m, 
                             h.v_m){
  vec1 <- c(m.icu, m.v, 0)
  vec2 <- c(h.icu_m, h.v_m, 1)
  vec3 <- c(1, 1, 1)
  
  ls <- rbind(vec1, vec2, vec3)
  rs <- rbind(m.v - 1, h.v_m, 1)
  
  sol <- t(solve(ls, rs))
  colnames(sol) <- c('p.v_icu', 'p.v_v', 'p.v_m')
  
  return(sol[1,])
  
}
```

```{r}
evalThirdSystem <- function(m.g, 
                            m.icu, 
                            m.v,
                            h.icu_v, 
                            h.g_m, 
                            h.icu_m, 
                            h.v_m,
                            p.g_g, 
                            p.g_icu){
  
  vec1 <- c(1, 1, 1, 1)
  vec2 <- c(m.g, m.icu, m.v, 0)
  vec3 <- c(p.g_icu * h.icu_v, h.icu_v * (1 - p.g_g), 1 - p.g_g, 0)
  vec4 <- c(h.g_m, h.icu_m, h.v_m, 1)
  
  ls <- rbind(vec1, vec2, vec3, vec4)
  rs <- c(1, m.icu - 1, (1 - p.g_g) * h.icu_v, h.icu_m)
  
  sol <- t(solve(ls, rs))
  colnames(sol) <- c('p.icu_g', 'p.icu_icu', 'p.icu_v', 'p.icu_m')
  
  return(sol[1,])
}
```


```{r}
evalThirdSystem(10, 7, 5, 0.6, 0.05, 0.2, 0.8, 0.7, 0.2)
```



```{r}
getTransition <- function(m.g, 
                          m.icu, 
                          m.v, 
                          h.g_m, 
                          h.g_icu, 
                          h.icu_m, 
                          h.icu_v,
                          h.v_m){
  
  sys1 <- evalFirstSystem(m.g, m.icu, h.g_m, h.g_icu, h.icu_m)
  sys2 <- evalSecondSystem(m.icu, m.v, h.icu_m, h.v_m)
  
  
  p.g_g <- sys1['p.g_g']
  p.g_icu <- sys1['p.g_icu']
  p.g_m <- sys1['p.g_m']
  p.g_d <- sys1['p.g_d']
  
  p.v_icu <- sys2['p.v_icu']
  p.v_v <- sys2['p.v_v']
  p.v_m <- sys2['p.v_m']
  
  sys3 <- evalThirdSystem(m.g, m.icu, m.v,h.icu_v, h.g_m, h.icu_m, h.v_m,p.g_g, p.g_icu)
  
  p.icu_g <- sys3['p.icu_g']
  p.icu_icu <- sys3['p.icu_icu']
  p.icu_v <- sys3['p.icu_v']
  p.icu_m <- sys3['p.icu_m']
  
  final.mat <- matrix(c(p.g_g, p.g_icu, 0, p.g_d, p.g_m,
                        p.icu_g, p.icu_icu, p.icu_v, 0, p.icu_m,
                        0, p.v_icu, p.v_v, 0, p.v_m,
                        0, 0, 0, 1, 0,
                        0, 0, 0, 0, 1),
                      ncol = 5, 
                      byrow = TRUE)
  
  return(final.mat)
  
}
```


```{r}
runMarkov <- function(new.hosp.vec, trans.mat){
  
  # h, icu, vent, d, m 
  df.final <- data.frame()
  
  step.vec <- c(0, 0, 0, 0, 0)

  for (hosp.val in new.hosp.vec){
    step.vec <- as.vector(step.vec %*% trans.mat)
    step.vec[1] <- step.vec[1] + hosp.val 
    df.final <- rbind(df.final, step.vec)
  }
  
  colnames(df.final) <- c('h', 'icu', 'vent', 'd', 'm')
  return(df.final)
}
```

```{r}
dum.mat <- matrix(rexp(25), 5)

dum.mat <- dum.mat / rowSums(dum.mat)
```



```{r}
SIR <- function(S0, I0, R0, beta.vector, gamma_r, gamma_h, trans.mat, num.days) {
  
  # initialize S, I, R 
  S <- I <- R <- H <- rep(NA_real_, num.days)
  S[1] <- S0
  I[1] <- I0
  R[1] <- R0
  H[1] <- 0
  
  gamma <- gamma_r + gamma_h

  # run SIR model 
  for (tt in 1:(num.days - 1)) {
    beta <- beta.vector[tt]
    S[tt + 1] <-  -beta * S[tt] * I[tt]                  + S[tt]
    I[tt + 1] <-   beta * S[tt] * I[tt] - gamma * I[tt]  + I[tt]
    R[tt + 1] <-                          gamma_r * I[tt]  + R[tt]
    H[tt + 1] <- gamma_h * I[tt]
  }
  
  df.return <- data.frame(days = 1:num.days, S, I, R, H)
  markov.df <- runMarkov(H, trans.mat)
  markov.df$days <- 1:num.days 
  
  print(df.return)
  print(markov.df)
  
  df.return <- merge(df.return, markov.df, by = 'days')
  df.return$R <- df.return$R + df.return$d
  df.return$d <- NULL
  df.return$H <- NULL
  
  return(df.return)
  
}
```

```{r}
test <- SIR(800000, 1, 0, rep(2e-7, 100), 1/28, 1/27, dum.mat, 100)
```



